version: '3.1'

services:
    residentdb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'resident'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        ports:
            - "3384:3306"
        volumes:
            - resident-db:/var/lib/residentdb
        container_name: residentdb
    gameapp:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: gameapp
        depends_on:
            collectordatabase:
                condition: service_healthy
        ports:
            - "8080:8080"
volumes:
    resident-db:


